### ISSUE TITLE
Can't run on Windows 10

### ISSUE THREAD

**Issue by alexeyco** [andlabs/ui#150] opened 2016-06-17 15:53 UTC
Hi there!
```
package main

import (
    "github.com/andlabs/ui"
)

func main() {
    err := ui.Main(func() {
        name := ui.NewEntry()
        button := ui.NewButton("Greet")
        greeting := ui.NewLabel("")
        box := ui.NewVerticalBox()
        box.Append(ui.NewLabel("Enter your name:"), false)
        box.Append(name, false)
        box.Append(button, false)
        box.Append(greeting, false)
        window := ui.NewWindow("Hello", 200, 100, false)
        window.SetChild(box)
        button.OnClicked(func(*ui.Button) {
            greeting.SetText("Hello, " + name.Text() + "!")
        })
        window.OnClosing(func(*ui.Window) bool {
            ui.Quit()
            return true
        })
        window.Show()
    })
    if err != nil {
        panic(err)
    }
}
```

```
C:\Users\***\Documents\Go\src\bitbucket.org\***\test>go build -x example.go
WORK=C:\Users\***\AppData\Local\Temp\go-build532876454
mkdir -p $WORK\command-line-arguments\_obj\
mkdir -p $WORK\command-line-arguments\_obj\exe\
cd C:\Users\***\Documents\Go\src\bitbucket.org\alexeyco\test
"C:\\Go\\pkg\\tool\\windows_amd64\\compile.exe" -o "C:\\Users\\***\\AppData\\Local\\Temp\\go-build532876454\\command-line-arguments.a" -trimpath "C:\\Users\\***\\AppData\\Local\\Temp\\go-build532876454" -p main -complete -buildid ef90b02de892f735b1c69040e30681a44a3af01c -D _/C_/Users/***/Documents/Go/src/bitbucket.org/alexeyco/test -I "C:\\Users\\***\\AppData\\Local\\Temp\\go-build532876454" -I "C:\\Users\\***\\Documents\\Go\\pkg\\windows_amd64" -pack "C:\\Users\\***\\Documents\\Go\\src\\bitbucket.org\\alexeyco\\test\\example.go"
cd .
"C:\\Go\\pkg\\tool\\windows_amd64\\link.exe" -o "C:\\Users\\***\\AppData\\Local\\Temp\\go-build532876454\\command-line-arguments\\_obj\\exe\\a.out.exe" -L "C:\\Users\\***\\AppData\\Local\\Temp\\go-build532876454" -L "C:\\Users\\***\\Documents\\Go\\pkg\\windows_amd64" -extld=g++ -buildmode=exe -buildid=ef90b02de892f735b1c69040e30681a44a3af01c "C:\\Users\\***\\AppData\\Local\\Temp\\go-build532876454\\command-line-arguments.a"
mv $WORK\command-line-arguments\_obj\exe\a.out.exe example.exe
```

But
```
> go run example.go
fork/exec C:\Users\***\AppData\Local\Temp\go-build813048770\command-line-arguments\_obj\exe\example.exe: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
```

```
> go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\***\Documents\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

```
> go version
go version go1.6.2 windows/amd64
```
What's wrong?

**Comment by andlabs** [comment] 2016-06-17 16:02
Duplicate of #142

**Closed by andlabs** 2016-06-17 16:02 UTC
