### ISSUE TITLE
go get fails on debian

### ISSUE THREAD

**Issue by jrmiller82** [andlabs/ui#241] opened 2017-07-21 20:33 UTC
```
% go get -u github.com/andlabs/ui
# github.com/andlabs/ui
/usr/bin/ld: go_path/src/github.com/andlabs/ui/libui_linux_amd64.a(libui-combined.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

Running debian unstable. Go 1.8.3.

**Comment by jrmiller82** [comment] 2017-07-21 20:46
See issue #230.

**Comment by andlabs** [comment] 2018-03-26 21:07
Duplicate of #230.

**Closed by andlabs** 2018-03-26 21:07 UTC
