### ISSUE TITLE
Listbox

### ISSUE THREAD

**Issue by CalebQ42** [andlabs/ui#151] opened 2016-06-18 06:56 UTC
Would it be possible to implement some sort of list box? Or if it's already implemented tell me what I'm overlooking.

**Comment by CalebQ42** [comment] 2016-06-22 04:21
Since it doesn't appear there is a list box, how possible would it be for me to create a listbox using a box or Area and a bunch of lables? This is actually an important part of a program I'm working on. I would prefer to use this ui instead of gxui (nelsam fork) which is what I'm currently using (but it's starting to bust at the seams a bit).

**Comment by andlabs** [comment] 2016-06-22 05:10
Don't do that; it'll never be like a real listbox. I'm working on a table control right now.

**Comment by c4rp3nt3r** [comment] 2016-10-19 11:58
hi anlabs，good job！but when do you upload the table control？

**Comment by JackMordaunt** [comment] 2017-03-11 09:14
Is there an update on the table control? I need a "ListView" / "TreeView" for my little app and I'm wondering if this is far off.

**Comment by ghiewa** [comment] 2017-07-09 17:08
@JackMordaunt looks like lots of guys waiting for that.

**Comment by taluttasgiran** [comment] 2017-08-06 13:38
@andlabs 👍 I'm waiting too. 😄

**Comment by bcampbell** [comment] 2018-01-01 02:59
Duplicate of #125?

**Comment by andlabs** [comment] 2018-03-23 19:40
Replaced with andlabs/libui#310.

**Closed by andlabs** 2018-03-23 19:40 UTC

**Comment by ajwillia-ms** [comment] 2018-08-23 13:49
Hi @CalebQ42 Did you find a workaround in the meantime? I too thought about a list of labels but the mouse handling seems impossible.

A list of buttons is the best I can think of...

**Comment by andlabs** [comment] 2018-08-23 15:26
I am working on adding tables to package ui now.

**Comment by bcampbell** [comment] 2018-08-23 18:42
@andlabs: Doubt it's much use to you, but: https://github.com/bcampbell/ui/tree/libui-table

**Comment by andlabs** [comment] 2018-08-23 19:03
I was going to take a different approach to specifying column types. Most of your code will work unchanged, though. I can review your code later to see if I can just use that instead.
