### ISSUE TITLE
Issue when go get

### ISSUE THREAD

**Issue by kkadosh** [andlabs/ui#309] opened 2018-07-13 08:42 UTC
While i'm trying to use this library, and `go get` it , i have the following error : 

```
# github.com/andlabs/ui
/usr/bin/ld: ./libui_linux_amd64.a(libui-combined.o): réadressage R_X86_64_32S vers « .rodata » ne peut pas être utilisé en créant un objet PIE; recompilez avec -fPIC
/usr/bin/ld : échec de l'édition de liens finale : Section non-représentable sur la sortie
collect2: error: ld returned 1 exit status
zsh: exit 2     go build

```

I'm on debian stretch and use golang 1.10.

**Comment by andlabs** [comment] 2018-07-13 10:32
Duplicate of #230

**Closed by andlabs** 2018-07-13 10:32 UTC
