### ISSUE TITLE
Needs instructions for building on Windows

### ISSUE THREAD

**Issue by Timmmm** [andlabs/ui#159] opened 2016-06-20 20:41 UTC
It would be really helpful to have instructions for how you can build this on Windows. I've tried the following approaches:

## mingw-w64

1. Install [mingw-w64](http://mingw-w64.org/doku.php). If you follow the unnecessarily long chain of 'Download' links, you eventually end up at [win-builds](http://win-builds.org/doku.php/download_and_installation_from_windows).
2. Install all the Win-builds packages. I initially tried installing just the GCC ones, but there's no dependency management so it doesn't pull in the required libraries (e.g. GPM). It's easier to install everything (yeah I know this is stupid).
3. `set CGO_ENABLED=1`
4. `go get github.com/andlabs/ui`

Unfortunately this gives an error something like this (at least I think this was the error; I've tried so many methods now...):

    c:\go\pkg\tool\windows_amd64\cgo.exe: exit status 2

## mingw32 from Qt

1. Download & install Qt
2. Add `C:\Qt\Tools\mingw492_32\bin` to `PATH`
3. `set CGO_ENABLED=1`
4. `set GOOS=windows`
5. `set GOARCH=386`
6. `go get github.com/andlabs/ui`

Unfortunately this gives linker errors, first to `_imp__TaskDialog@32`, apparently because that version of GCC is too old, and also to C++11 iostreams stuff:

```
C:/Users/Tim/gocode/src/github.com/andlabs/ui/libui_windows_386.a(stddialogs.cpp.obj): In function `msgbox':
E:/github.com/andlabs/libui/windows/stddialogs.cpp:113: undefined reference to `_imp__TaskDialog@32'
C:/Users/Tim/gocode/src/github.com/andlabs/ui/libui_windows_386.a(alloc.cpp.obj): In function `Z11uninitAllocv':
E:/github.com/andlabs/libui/windows/alloc.cpp:16: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode)'
E:/github.com/andlabs/libui/windows/alloc.cpp:17: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
E:/github.com/andlabs/libui/windows/alloc.cpp:24: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str() const'
E:/github.com/andlabs/libui/windows/alloc.cpp:24: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
E:/github.com/andlabs/libui/windows/alloc.cpp:24: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
E:/github.com/andlabs/libui/windows/alloc.cpp:25: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
E:/github.com/andlabs/libui/windows/alloc.cpp:25: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
E:/github.com/andlabs/libui/windows/alloc.cpp:17: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()'
E:/github.com/andlabs/libui/windows/alloc.cpp:24: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
E:/github.com/andlabs/libui/windows/alloc.cpp:17: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
E:/github.com/andlabs/libui/windows/alloc.cpp:16: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()'
C:/Users/Tim/gocode/src/github.com/andlabs/ui/libui_windows_386.a(utf16.cpp.obj): In function `Z8ftoutf16d':
E:/github.com/andlabs/libui/windows/utf16.cpp:136: undefined reference to `std::__cxx11::basic_ostringstream<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_ostringstream(std::_Ios_Openmode)'
E:/github.com/andlabs/libui/windows/utf16.cpp:137: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_string()'
E:/github.com/andlabs/libui/windows/utf16.cpp:140: undefined reference to `std::__cxx11::basic_ostringstream<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::str() const'
E:/github.com/andlabs/libui/windows/utf16.cpp:140: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::operator=(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&&)'
E:/github.com/andlabs/libui/windows/utf16.cpp:140: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_string()'
E:/github.com/andlabs/libui/windows/utf16.cpp:141: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::c_str() const'
E:/github.com/andlabs/libui/windows/utf16.cpp:137: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_string()'
E:/github.com/andlabs/libui/windows/utf16.cpp:136: undefined reference to `std::__cxx11::basic_ostringstream<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_ostringstream()'
E:/github.com/andlabs/libui/windows/utf16.cpp:140: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_string()'
E:/github.com/andlabs/libui/windows/utf16.cpp:137: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_string()'
E:/github.com/andlabs/libui/windows/utf16.cpp:136: undefined reference to `std::__cxx11::basic_ostringstream<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_ostringstream()'
C:/Users/Tim/gocode/src/github.com/andlabs/ui/libui_windows_386.a(utf16.cpp.obj): In function `Z8itoutf16x':
E:/github.com/andlabs/libui/windows/utf16.cpp:147: undefined reference to `std::__cxx11::basic_ostringstream<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_ostringstream(std::_Ios_Openmode)'
E:/github.com/andlabs/libui/windows/utf16.cpp:148: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_string()'
E:/github.com/andlabs/libui/windows/utf16.cpp:151: undefined reference to `std::__cxx11::basic_ostringstream<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::str() const'
E:/github.com/andlabs/libui/windows/utf16.cpp:151: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::operator=(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&&)'
E:/github.com/andlabs/libui/windows/utf16.cpp:151: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_string()'
E:/github.com/andlabs/libui/windows/utf16.cpp:152: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::c_str() const'
E:/github.com/andlabs/libui/windows/utf16.cpp:148: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_string()'
E:/github.com/andlabs/libui/windows/utf16.cpp:147: undefined reference to `std::__cxx11::basic_ostringstream<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_ostringstream()'
E:/github.com/andlabs/libui/windows/utf16.cpp:151: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_string()'
E:/github.com/andlabs/libui/windows/utf16.cpp:148: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_string()'
E:/github.com/andlabs/libui/windows/utf16.cpp:147: undefined reference to `std::__cxx11::basic_ostringstream<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_ostringstream()'
collect2.exe: error: ld returned 1 exit status
```

## ming32

1. Download and install [this version of mingw](https://sourceforge.net/projects/mingw/files/latest/download)
2. Add `C:\MinGW\bin` to `PATH`
3. `set CGO_ENABLED=1`
4. `set GOOS=windows`
5. `set GOARCH=386`
6. `go get github.com/andlabs/ui`

Unfortunately this gives these errors:

```
# github.com/andlabs/ui
c:/mingw/bin/../lib/gcc/mingw32/4.9.3/../../../../mingw32/bin/ld.exe: cannot find -ld2d1
c:/mingw/bin/../lib/gcc/mingw32/4.9.3/../../../../mingw32/bin/ld.exe: cannot find -ldwrite
collect2.exe: error: ld returned 1 exit status
```

As you can see it is very difficult to compile this package on Windows. Clear instructions would be very helpful.

**Comment by andlabs** [comment] 2016-06-20 20:45
MinGW-w64 is the only supported method, however for whatever reason an important commit is missing from the win-builds version that's present in the MSYS2 version; try that one instead. In the meantime, duplicate of #147 (and others). Thanks for reporting!

**Closed by andlabs** 2016-06-20 20:45 UTC
