### ISSUE TITLE
mac osx 10.13.3 build error

### ISSUE THREAD

**Issue by cjmxp** [andlabs/ui#271] opened 2018-02-21 12:15 UTC
mac osx 10.13.3 build error 
invalid flag in #cgo LDFLAGS: -mmacosx-version-min=10.8

**Comment by andlabs** [comment] 2018-02-21 12:22
Duplicate of https://github.com/golang/go/issues/23749. Upgrade to Go 1.10 for now.

**Comment by cjmxp** [comment] 2018-02-21 12:41
@andlabs go version go1.10 darwin/amd64

**Comment by andlabs** [comment] 2018-02-21 12:44
Will investigate later.

**Comment by andlabs** [comment] 2018-02-21 16:02
Okay, the Go team is aware and will fix it soon.

**Closed** 2018-02-22 00:59 UTC
