### ISSUE TITLE
A question about “ui.NewTab()”

### ISSUE THREAD

**Issue by Releasel0ck** [andlabs/ui#311] opened 2018-07-31 13:52 UTC
My code is as follows:
`
tab := ui.NewTab()
vb1 := ui.NewVerticalBox()
lb := ui.NewLabel("Label")
vb1.Append(lb, false)		
tab.Append("page1", vb1)
`
But when my program is running,page1 is blank!There is no Label control.
What is wrong with my code?

**Comment by andlabs** [comment] 2018-07-31 16:35
What OS?

**Comment by Releasel0ck** [comment] 2018-08-01 00:07
@andlabs Build and run on " Windows 10 X64"

**Comment by CheatCoder** [comment] 2018-08-03 14:52
What gcc/g++ compiler are you using? 

On my Windows 10 x64, the tabs are working correctly.
And can i see go run/build with the -x flag ? Don't forget to remove the "username" from the paths :)

**Comment by Releasel0ck** [comment] 2018-08-04 07:51
@CheatCoder 
Is that the meaning of this？
![1](https://user-images.githubusercontent.com/19485482/43673947-29d178c0-97fe-11e8-93b3-779ccc311102.png)
![2](https://user-images.githubusercontent.com/19485482/43673948-2bc4f526-97fe-11e8-9ad3-10da1159e33a.png)

**Comment by Releasel0ck** [comment] 2018-08-04 08:55
@andlabs @CheatCoder 
Thank you for your warm answer!I found the problem.The gcc/g++ I used before is mingw32. When I add a parameter ‘-x’, I have an error "cc1.exe: sorry, unimplemented: 64-bit mode not compiled in".When I corrected this mistake, the tabs are working correctly.

**Comment by andlabs** [comment] 2018-08-04 14:14
That's odd; the program shouldn't even start if that was the error...

**Comment by CheatCoder** [comment] 2018-08-10 16:40
Sorry, I had no internet. But when the problem is solved, we can close the issue now.

**Closed** 2018-08-18 04:47 UTC
