### ISSUE TITLE
OSX: ld: warning: object file (...) was built for newer OSX version (10.13) than being linked (10.8)

### ISSUE THREAD

**Issue by emf42** [andlabs/ui#294] opened 2018-05-19 06:28 UTC
Whenever I run any files which import ui, my console gets flooded with linker warnings:
```
ld: warning: object file (/var/folders/g4/2y67jwvx46b6hpfbp_ycslzc0000gn/T/go-link-078172606/000024.o) was built for newer OSX version (10.13) than being linked (10.8)
```

The programs still work, and the gui opens, I just want a way to make these warnings go away. 

The initial error when I did go get on this package was 
```
ld: warning: object file ($GOPATH/go/src/github.com/andlabs/ui/libui_darwin_amd64.a(libui-combined.o)) was built for newer OSX version (10.12) than being linked (10.8)
```

**Comment by andlabs** [comment] 2018-05-19 12:28
Duplicate of #111

**Comment by andlabs** [comment] 2018-05-19 12:31
Duplicate of andlabs/libui#111

**Closed by andlabs** 2018-05-19 12:31 UTC

**Comment by andlabs** [comment] 2018-05-19 12:33
I thought that issue was on this repo the whole time, huh...
