### ISSUE TITLE
Value of radio buttons cannot be retrieved

### ISSUE THREAD

**Issue by MrVegetables** [andlabs/ui#200] opened 2016-10-21 18:01 UTC
Maybe I'm missing something in the documentation, but the `RadioButtons` type has only those methods that let it satisfy `Control` and `Append(string)`. As far as I can tell, there's no way to get the currently selected value, or register a function to be run when a new value is selected.

**Comment by andlabs** [comment] 2016-10-21 20:11
In libui. Will come to package ui soon. Duplicate of lots of other issues.

**Closed by andlabs** 2016-10-21 20:11 UTC
