### ISSUE TITLE
Build linux execution file on debian 9 failed

### ISSUE THREAD

**Issue by trigun117** [andlabs/ui#282] opened 2018-03-27 19:20 UTC
Failed to create execution file on linux in docker container.

Container run with this command: `docker run -ti -v path/to/files:/go/src golang bash`, golang is official image with last golang version.

`go get -v -u github.com/andlabs/ui` **works only like this:** `GOOS=windows CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go get -v -u github.com/andlabs/ui`

Execution files for windows builds normal by: `GOOS=windows CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -ldflags -H=windowsgui`

When try to change GOOS to linux got this:
```
# runtime/cgo
gcc_linux_amd64.c: In function '_cgo_sys_thread_start':
gcc_linux_amd64.c:62:2: error: unknown type name 'sigset_t'
  sigset_t ign, oset;
  ^~~~~~~~
gcc_linux_amd64.c:67:2: error: implicit declaration of function 'sigfillset' [-Werror=implicit-function-declaration]
  sigfillset(&ign);
  ^~~~~~~~~~
gcc_linux_amd64.c:62:16: error: unused variable 'oset' [-Werror=unused-variable]
  sigset_t ign, oset;
                ^~~~
cc1: all warnings being treated as errors
```

**Installed**: libgtk-3-dev, mingw-w64

go env:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build817048499=/tmp/go-build -gno-record-gcc-switches"
```
uname -a:
`Linux 4b0d492ecd42 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 GNU/Linux`

**Comment by andlabs** [comment] 2018-03-27 19:57
How are you running the Linux build?

**Comment by trigun117** [comment] 2018-03-27 20:04
`GOOS=linux CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build`

**Comment by andlabs** [comment] 2018-03-27 20:19
You are trying to build Linux code with a Windows compiler. Remove the environment variables.

**Comment by trigun117** [comment] 2018-03-27 20:36
go build:
```
# github.com/andlabs/ui
/usr/bin/ld: github.com/andlabs/ui/libui_linux_amd64.a(libui-combined.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

**Comment by andlabs** [comment] 2018-03-27 20:57
In that case, duplicate of #230.

**Closed by andlabs** 2018-03-27 20:57 UTC
