### ISSUE TITLE
build error with libui_windows_386.a

### ISSUE THREAD

**Issue by nowind** [andlabs/ui#356] opened 2019-05-26 13:31 UTC
output with following err
libui_windows_386.a(attrstr.cpp.obj):attrstr.cpp:(.eh_frame+0x13): more undefined references to `__gxx_personality_v
0' follow

**Comment by andlabs** [comment] 2019-05-26 13:54
Duplicate of #281

**Closed by andlabs** 2019-05-26 13:54 UTC
