### ISSUE TITLE
go get failed in windows 64

### ISSUE THREAD

**Issue by bruceauyeung** [andlabs/ui#190] opened 2016-09-05 02:28 UTC
os: windows 7 64bit
go: 1.7 windows amd64
gcc: gcc (tdm64-1) 5.1.0

error messages:

> # runtime
> D:\go\src\runtime\lfstack_amd64.go:16: lfstackPack redeclared in this block
>         previous declaration at D:\go\src\runtime\lfstack_64bit.go:37
> D:\go\src\runtime\lfstack_amd64.go:20: lfstackUnpack redeclared in this block
>         previous declaration at D:\go\src\runtime\lfstack_64bit.go:41
> D:\go\src\runtime\os_windows.go:14: _NSIG redeclared in this block
>         previous declaration at D:\go\src\runtime\os2_windows.go:18
> D:\go\src\runtime\os_windows.go:104: _AddVectoredExceptionHandler redeclared in this block
>         previous declaration at D:\go\src\runtime\os1_windows.go:92
> D:\go\src\runtime\os_windows.go:104: _CloseHandle redeclared in this block
>         previous declaration at D:\go\src\runtime\os1_windows.go:92
> D:\go\src\runtime\os_windows.go:104: _CreateEventA redeclared in this block
>         previous declaration at D:\go\src\runtime\os1_windows.go:92
> D:\go\src\runtime\os_windows.go:104: _CreateIoCompletionPort redeclared in this block
>         previous declaration at D:\go\src\runtime\os1_windows.go:92
> D:\go\src\runtime\os_windows.go:104: _CreateThread redeclared in this block
>         previous declaration at D:\go\src\runtime\os1_windows.go:92
> D:\go\src\runtime\os_windows.go:104: _CreateWaitableTimerA redeclared in this block
>         previous declaration at D:\go\src\runtime\os1_windows.go:92
> D:\go\src\runtime\os_windows.go:104: _CryptAcquireContextW redeclared in this block
>         previous declaration at D:\go\src\runtime\os1_windows.go:92
> D:\go\src\runtime\os_windows.go:104: too many errors

**Comment by redhatlinux10** [comment] 2016-09-05 02:47
sorry, the error mentioned above was caused by incorrect golang installation. but after i reinstalled my golang, there was another error:

> go build github.com/andlabs/ui
\# github.com/andlabs/ui
D:/go-path-ext/src/github.com/andlabs/ui/libui_windows_amd64.a(stddialogs.cpp.obj): In function `msgbox':
E:/github.com/andlabs/libui/windows/stddialogs.cpp:113: undefined reference to `__imp_TaskDialog'
collect2.exe: error: ld returned 1 exit status

**Comment by TarabyteCoding** [comment] 2016-10-14 22:20
Same issue here. Trying to do a go get and receiving: 

> go get github.com/andlabs/ui
# github.com/andlabs/ui
C:/go_lib/src/github.com/andlabs/ui/libui_windows_amd64.a(stddialogs.cpp.obj): In function `msgbox':
E:/github.com/andlabs/libui/windows/stddialogs.cpp:113: undefined reference to `__imp_TaskDialog'
collect2.exe: error: ld returned 1 exit status

**Comment by andlabs** [comment] 2016-10-14 22:38
@redhatlinux10 that trace is from an attempt to build package runtime. How are you installing Go?

@TarabyteCoding see #147

**Comment by andlabs** [comment] 2016-10-21 20:17
@redhatlinux10 did you extract a Go source tarball over another Go source tarball? https://github.com/andlabs/ui/issues/185

**Comment by bruceauyeung** [comment] 2016-11-02 08:47
@andlabs the first error was caused by directly extracting tarball into already existed golang installation directory, and i realized that, so i delete the whole original directory and then the first error disappeared. but the second error cames.

**Comment by andlabs** [comment] 2016-11-02 11:08
So now you get the TaskDialog error?

**Comment by silverkorn** [comment] 2017-01-09 17:24
I'm also having the issue `[...]/ui/libui_windows_amd64.a(stddialogs.cpp.obj): In function `msgbox': [...]/libui/windows/stddialogs.cpp:113: undefined reference to__imp_TaskDialog'`.

Info:
go version go1.6.2 windows/amd64

Environment:
Go installed manually to `C:\Users\USERNAME\Apps\Go\`.
GOROOT=C:\Users\USERNAME\Apps\Go
GOPATH=C:\Users\USERNAME\Development\Standalone\GoTest

**Comment by andlabs** [comment] 2017-01-09 17:52
Again, install the latest MinGW-w64.

**Comment by silverkorn** [comment] 2017-01-10 20:23
Ok, it worked with the latest MinGW-w64 from __MSYS2__ (GCC 6.2.0).
I've been trying with the latest __TDM-GCC__ (GCC 5.1.0) but, indeed, it's a bit old and it doesn't work.

**Comment by andlabs** [comment] 2018-03-26 15:51
Merged with #279.

**Closed by andlabs** 2018-03-26 15:51 UTC
