### ISSUE TITLE
Requires GTK+ 3.0 installed on Fedora 24. How to install it?

### ISSUE THREAD

**Issue by vodolaz095** [andlabs/ui#216] opened 2017-01-19 15:26 UTC
```
[vodolaz095@steel ui]$ go test
# pkg-config --cflags gtk+-3.0
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
pkg-config: exit status 1
FAIL	github.com/andlabs/ui [build failed]
```

**Comment by vodolaz095** [comment] 2017-01-19 15:48
possible fix (fedora 24) is 

```shell

  # dnf install gtk3 gtk3-devel

```

**Comment by andlabs** [comment] 2017-01-19 18:18
(just to note that this is not a bug but rather a prerequisite — GTK+ is required to use package ui; I don't know the correct Fedora commands, sorry)

**Comment by sndnvaps** [comment] 2017-01-20 01:18
dnf search gtk+-3.0
it that possible

**Comment by andlabs** [comment] 2018-03-27 14:37
`sudo dnf install gtk3-devel`

Closing as duplicate of resolved #255.

**Closed by andlabs** 2018-03-27 14:37 UTC
