### ISSUE TITLE
Window closing when hitting enter

### ISSUE THREAD

**Issue by jordyvandomselaar** [andlabs/ui#198] opened 2016-10-13 13:49 UTC
When my program runs it quits as soon as someone hits enter.

Log: ```r9      0x13                                                                                                                          
r10     0x0                                                                                                                           
r11     0x64                                                                                                                          
r12     0x16095c                                                                                                                      
r13     0x111                                                                                                                         
r14     0x0                                                                                                                           
r15     0x0                                                                                                                           
rip     0x7ffb6ce46142                                                                                                                
rflags  0x202                                                                                                                         
cs      0x33                                                                                                                          
fs      0x53                                                                                                                          
gs      0x2b                                                                                                                          
exit status 2                                                                                                                         
               ```                                                                                                              
               `

**Comment by andlabs** [comment] 2016-10-13 13:56
Duplicate of #131

**Closed by andlabs** 2016-10-13 13:56 UTC
