### ISSUE TITLE
Build failing on High Sierra

### ISSUE THREAD

**Issue by ajwillia-ms** [andlabs/ui#313] opened 2018-08-15 13:52 UTC
On 10.13.6 I see the following error

➜  ui git:(master) go build        
go build github.com/andlabs/ui: invalid flag in #cgo LDFLAGS: -mmacosx-version-min=10.8

If I remove the -mmacosx-version-min from link_darwin_amd64.go the build succeeds.

**Comment by andlabs** [comment] 2018-08-15 13:57
Duplicate of golang/go#23749. Update your Go.

**Closed by andlabs** 2018-08-15 13:57 UTC

**Comment by ajwillia-ms** [comment] 2018-08-15 14:55
Thank you for that - I had not noticed that the cgo updated covered the mac specifics.
Updating to 1.10.3 fixed it.
