### ISSUE TITLE
Error: undefined reference to `__imp_TaskDialog'

### ISSUE THREAD

**Issue by brunocassol** [andlabs/ui#308] opened 2018-07-12 20:50 UTC
Just tried running the the [example code](https://github.com/andlabs/ui/wiki/Getting-Started) and got this error:

```
C:\Users\dev\go\src\github.com\brunocassol\gopic>go run main.go
# github.com/andlabs/ui
C:/Users/dev/go/src/github.com/andlabs/ui/libui_windows_amd64.a(stddialogs.cpp.obj): In function `msgbox':
E:/github.com/andlabs/libui/windows/stddialogs.cpp:113: undefined reference to `__imp_TaskDialog'
collect2.exe: error: ld returned 1 exit status
```

I'm using:

-  Go 1.10.3
- Windows 10 64bits
- MingW GCC 5.1.0 from [http://tdm-gcc.tdragon.net/download](http://tdm-gcc.tdragon.net/download)
-  Installed ui with: `go get -u -v "github.com/andlabs/ui"`

`gcc -v` returns:

```
Using built-in specs.
COLLECT_GCC=C:\TDM-GCC-64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/TDM-GCC-64/bin/../libexec/gcc/x86_64-w64-mingw32/5.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-5.1.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-cxx-flags=-DWINPTHREAD_STATIC --disable-build-with-cxx --disable-build-poststage1-with-cxx --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --prefix=/mingw64tdm --with-local-prefix=/mingw64tdm --with-pkgversion=tdm64-1 --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: posix
gcc version 5.1.0 (tdm64-1)
```

**Comment by andlabs** [comment] 2018-07-13 02:15
Duplicate of #281

**Comment by andlabs** [comment] 2018-07-13 02:17
Duplicate of #279 (correct issue this time)

**Closed by andlabs** 2018-07-13 02:17 UTC
