### ISSUE TITLE
rodata' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by r3mb00** [andlabs/ui#301] opened 2018-05-25 14:37 UTC
Hi.

I did all steps but got:

![screenshot at 2018-05-25 14-38-09](https://user-images.githubusercontent.com/9653037/40550231-104915e6-6029-11e8-9083-e3ff3c567c67.png)

Can anyone help?

**Comment by andlabs** [comment] 2018-05-25 18:43
Duplicate of #230

**Closed by andlabs** 2018-05-25 18:43 UTC
