### ISSUE TITLE
Mac OSX get failed ...invalid flag in ... 

### ISSUE THREAD

**Issue by bejea** [andlabs/ui#303] opened 2018-05-30 08:43 UTC
go build github.com/andlabs/ui: invalid flag in #cgo LDFLAGS: -mmacosx-version-min=10.8

**Comment by andlabs** [comment] 2018-05-30 10:41
Update your version of Go.

**Comment by andlabs** [comment] 2018-05-30 10:41
Update your version of Go.

Duplicate of golang/go#23749

**Closed by andlabs** 2018-05-30 10:41 UTC
